Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('BoardConfig', src, depend = ['RT_USING_BOARD_TEST1'], CPPPATH = CPPPATH)

Return('group')
