Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

if GetDepend(['RT_USING_RKADK']):
    src += Glob('lv_port_disp/rkadk/*.c')
    CPPPATH += [cwd + '/lv_port_disp/rkadk']
else:
    src += Glob('lv_port_disp/vop/*.c')
    CPPPATH += [cwd + '/lv_port_disp/vop']

group = DefineGroup('Applications', src, depend = ['RT_USING_LVGL_DEMO'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
