Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]
group = []

group = DefineGroup('ptpd', src, depend = ['RT_USING_LWIP_PTP'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')) and GetDepend('RT_USING_LWIP_PTP'):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
